import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

self.skipWaiting()
clientsClaim()

cleanupOutdatedCaches()

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST)

// Push Notification Event Listener
// Push Notification Event Listener
self.addEventListener('push', (event) => {
    console.log('[SW] Push Received', event);
    let data = {}
    try {
        if (event.data) {
            // Case 1: Try JSON
            try {
                data = event.data.json()
            } catch (e) {
                // Case 2: Plain Text
                console.warn('[SW] Payload is not JSON, treating as text.')
                data = {
                    title: 'Notification',
                    body: event.data.text()
                }
            }
        } else {
            // Case 3: Empty/Null
            console.warn('[SW] Push received with no payload.')
            data = {
                title: 'New Notification',
                body: 'You have a new message'
            }
        }
        console.log('[SW] Parsed Data:', data)
    } catch (e) {
        console.error('[SW] Critical error parsing push data', e)
        data = { title: 'Error', body: 'New notification available' }
    }

    const title = data.title || 'SUNOMSI'

    // Robust URL extraction: Handle flat structure or nested 'data' object (FCM style)
    const payload = data.data || data
    const targetUrl = payload.url || data.url || '/'

    const options = {
        body: data.body || 'New update available',
        icon: '/logo.png',
        badge: '/logo.png',
        data: {
            url: targetUrl
        }
    }

    event.waitUntil(
        self.registration.showNotification(title, options)
            .then(() => console.log('[SW] Notification shown'))
            .catch(err => console.error('[SW] Error showing notification:', err))
    )
})

// Notification Click Event Listener
self.addEventListener('notificationclick', (event) => {
    event.notification.close()

    const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i]
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus()
                }
            }
            // If not, open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen)
            }
        })
    )
})
