import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

self.skipWaiting()
clientsClaim()

cleanupOutdatedCaches()

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST)

// Push Notification Event Listener
// Push Notification Event Listener
self.addEventListener('push', (event) => {
    console.log('[SW] Push Received', event);
    let data = {}
    try {
        data = event.data ? event.data.json() : {}
        console.log('[SW] Push Data:', data);
    } catch (e) {
        console.error('[SW] Error parsing push data', e);
        data = { title: 'New Notification', body: event.data ? event.data.text() : 'You have a new message' }
    }

    const title = data.title || 'SUNOMSI'
    const options = {
        body: data.body || 'New update available',
        icon: '/logo.png', // Fixed: pwa-192x192.png didn't exist
        badge: '/logo.png',
        data: {
            url: data.url || '/'
        }
    }

    event.waitUntil(
        self.registration.showNotification(title, options)
            .then(() => console.log('[SW] Notification shown'))
            .catch(err => console.error('[SW] Error showing notification:', err))
    )
})

// Notification Click Event Listener
self.addEventListener('notificationclick', (event) => {
    event.notification.close()

    const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i]
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus()
                }
            }
            // If not, open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen)
            }
        })
    )
})
